#version: "3.0"
services:
  db:
    container_name: "finance_db"
    image: postgres:16.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2726
      - POSTGRES_DB=finance
    ports:
      - "1111:5432"
    networks:
      - custom
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    network_mode: "host"  # Add this line
    volumes:
      - .:/app
    env_file: # Load environment variables from .env file
      - .env
    depends_on:
      - db
networks:
  custom:
    driver: bridge
